### PR TITLE
Avoid the infinite loop if the build fails

### PR DESCRIPTION
**Pull request by JoaquinRivesGambin**
Split build and apply commands, so that it will exit the infinite loop if the build part fails.

### CODE REVIEW

**Comment by dmuiruri** [comment]
I think there is a need to address the risk of getting into an infinite loop before we can merge.

**Comment by JoaquinRivesGambin** [comment]
@dmuiruri As we have already merged the documentation which depends on this code, can we merge this now an create an [issue](https://github.com/OSS-MLOPS-PLATFORM/oss-mlops-platform/issues) for the bigger infinite apply loop problem?

I know this only fixes the infinite loop problem when caused because of errors in the building of the manifests, but solving the race condition problem in the main `kubectl apply` loop is going to be harder and take some more time. We can create another issue just for that, and discuss there possible solutions.

**Comment by dmuiruri** [comment]
I guess we can also handle the matter as an issue. So for that reason, we can merge current code.

**Review by dmuiruri — APPROVED** [review]
The building and application steps have been separated, this way, if the application fails, it does not try to rebuild the deployment.

**Pull request merged**
