### PR TITLE
21 modular install

### PR DESCRIPTION
**Pull request by JoaquinRivesGambin**
This solves the issue the "[Recommended number of CPUs required to run the pipeline too high](https://github.com/OSS-MLOPS-PLATFORM/oss-mlops-platform/issues/21)". Now, the users can choose different installation options:

> Please choose the deployment option:
> [1] Kubeflow (all components)
> [2] Kubeflow (without monitoring)
> [3] Standalone KFP
> [4] Standalone KFP (without monitoring)
> [5] Standalone KFP and Kserve
> [6] Standalone KFP and Kserve (without monitoring)
> Enter the number of your choice [1-6] (default is [1]): 

Other improvements:

- changed cluster name from old `kind-kind-ep` to `kind-mlops-platform`
- added `uninstall.sh` script to remove the cluster and the local docker repository if present
- improved the message error of the infinite loop:

>       Retrying to apply resources.
>       Be patient, this might take a while... (Errors are expected until all resources are available!)
>       
>       Help:
>         If the errors persists, please check the pods status with: kubectl get pods --all-namespaces
>         All pods should be either in Running state, or ContainerCreating if they are still starting up.
>         Check specific pod errors with: kubectl describe pod -n [NAMESPACE] [POD_NAME]
>       echo "  For further help, see the Troubleshooting section in setup.md"
>       echo

### CODE REVIEW

**Review by dmuiruri — CHANGES_REQUESTED** [review]
Typo on "University" of Helsinki
 If a link to the research group is desired: (https://www.helsinki.fi/en/researchgroups/empirical-software-engineering)

**Comment by JoaquinRivesGambin** [comment]
> Typo on "University" of Helsinki If a link to the research group is desired: (https://www.helsinki.fi/en/researchgroups/empirical-software-engineering)

Good catch, I will fix and add the link

**Comment by K123AsJ0k1** [comment]
Setup.sh option 6 tested on a laptop. I wonder if setup.md should mention the requested amount of CPU and RAM?

**Review by K123AsJ0k1 — APPROVED** [review]
Setup.sh (options 3-6 tested) and uninstall.sh work as expected, while file additions and notebooks look good, so approved.

**Comment by JoaquinRivesGambin** [comment]
> Setup.sh options 3-6 tested on a laptop. I wonder if setup.md should list the requested amount of CPU and RAM for these options or atleast mention that these can be checked with:
> 
> ```
> kubectl describe nodes
> ```

Sure, I will add the recommended CPU and memory also on the setup README

**Review by dmuiruri — APPROVED** [review]

**Comment by dmuiruri** [comment]
Tested all the modular installation configurations [1]- [6] on the CSC environment, and they were successful

**Pull request merged**
